language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: tip
  allow_failures:
  - go: tip
before_install:
- go get github.com/mitchellh/gox github.com/tcnksm/ghr github.com/Fyb3roptik/swaggomnia/models github.com/ghodss/yaml github.com/urfave/cli
install:
-
script:
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows openbsd freebsd"
  -arch="amd64" -output="logshare.." -ldflags "-X main.Rev=`git rev-parse --short
  HEAD`" -verbose ./...; fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "aQU95XXaZkBNko9OzDJQEvBm6up3gtvEi4dTfOoQTC0RAMSXPG+/FGZQaE3QN158X5NuB8KxE742bXl0RGjpxtdQGWQjItjYfARj43v7ADE4AHIKMEkdGBLqyfwQ9AEH/xpsr/svKM/dxVv5WEt5vkLwfzHqsZb9k3MOtQJO7agTBWBqtnCX3VFz+pvS8nzDPAPNYO39rEH89bvTCxl/LfpmCcG3pEFmajosC4+QZ1i6v/HH1UvYf/s04XOXf1oBjHKdT5lSopv4Bi0SDH1d9wpwqHEe2iMMgQc2+Y1eWyF3uQKbHd3bPfIi9VLkqn8gMq1xgN5qPnnacTV849hLCp5ZSPnczXjLKjagUWSK29b+5r7Ljb7a1VGyupzD/28jATYuVFxmCwLpb4mfXe/02WLLb+2PTdgDUfAp/i2kopgISAUte0bVY74Eyo2a/ppPJbPUwXS5KeUZ6Kvg5uj9qN0oR8AYYe69gT3IZx8FSgkRn/VNQZXbdhcsGi0oNUuFmcxbDb2bleD49Ev0eHFo5xLmPkADLZHt/oxPQUMLnY5pS21E0HB6VIxtTEd5M18IEMrbYZnapC0PZEnMDP2k4liKz7/nKXBHGJF2T9ycaMWJEYBw0v820YVeNFputoJRR/6TKbkJcwUmTaoXAf7dOpUQaJW6KevpMgeiOe66Kxk="
  file:
  - swaggomnia.windows.amd64.exe
  - swaggomnia.darwin.amd64
  - swaggomnia.linux.amd64
  - swaggomnia.openbsd.amd64
  - swaggomnia.freebsd.amd64
  on:
    repo: Fyb3roptik/swaggomnia
    tags: true
    condition: "$LATEST = true"
